
COMPILE_MODE = lib

ONLY_ARCHIVE = 1

REQUIRE_C = 1

OBJECT_SOURCES =           \
	runtime.c          \
	$(NULL)

PUBLIC_HEADERS =           \
	runtime.h          \
	$(NULL)

include ../../../common.make
