
ONLY_ARCHIVE = 1

COMPILE_MODE = lib

REQUIRE_C = 1

OBJECT_SOURCES =      \
	zn_list.c     \
	zn_hash.c     \
	$(NULL)

PUBLIC_HEADERS =      \
	zn_list.h     \
	zn_hash.h     \
	zn_mem.h      \
	$(NULL)

TEST_SOURCES = \
	zn_hash_test.c \
	$(NULL)

include ../../../common.make
