
COMPILE_MODE = lib

ONLY_ARCHIVE = 1

REQUIRE_C = 1

LYOBJ = zn_parser

OBJECT_SOURCES =           \
	zn_dispatcher.c    \
	zn_statement.c     \
	$(NULL)

PUBLIC_HEADERS =           \
	zn_dispatcher.h    \
	zn_parser.h        \
	$(NULL)

include ../../../common.make
