
COMPILE_MODE = lib

ONLY_ARCHIVE = 1

REQUIRE_C = 1

LYOBJ = zinc_grammar

OBJECT_SOURCES =           \
	zn_parser.c        \
	$(NULL)

PUBLIC_HEADERS =           \
	zn_parser.h        \
	$(NULL)

include ../../../common.make
