
COMPILE_MODE = lib

ONLY_ARCHIVE = 1

REQUIRE_C = 1

LYOBJ = zn_parser
PARSER_PREFIX = zn

OBJECT_SOURCES =           \
	zn_dispatcher.c    \
	zn_statement.c     \
	zn_param.c         \
	$(NULL)

PUBLIC_HEADERS =           \
	zn_dispatcher.h    \
	zn_parser.h        \
	zn_statement.h     \
	zn_param.h         \
	$(NULL)

include ../../../common.make
